In [24]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/corazzon/boostcourse-ds-510/master/data/medical_201909.csv.zip", low_memory=False)
df.shape
df.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,19956873,하나산부인과,NaN,S,의료,S01,병원,S01B10,산부인과,Q86201,...,4127310900110810000010857,산호한양아파트,경기도 안산시 단원구 달미로 10,425764.0,15236.0,NaN,NaN,NaN,126.814295,37.336344
1,20024149,타워광명내과의원,NaN,S,의료,S01,병원,S01B07,내과/외과,Q86201,...,1168011800104670014000001,NaN,서울특별시 강남구 언주로30길 39,135270.0,6292.0,NaN,4,NaN,127.053198,37.488742
2,20152277,조정현신경외과의원,NaN,S,의료,S01,병원,S01B15,신경외과,Q86201,...,4139013200117400001017064,한라프라자,경기도 시흥시 중심상가로 178,429450.0,15066.0,NaN,NaN,NaN,126.734841,37.344955
3,20350610,한귀원정신과의원,NaN,S,의료,S01,병원,S01B99,기타병원,NaN,...,2650010400100740001009932,NaN,부산광역시 수영구 수영로 688,613100.0,48266.0,NaN,5,NaN,129.115438,35.166872
4,20364049,더블유스토어수지점,수지점,S,의료,S02,약국/한약방,S02A01,약국,G47811,...,4146510100107120002026238,NaN,경기도 용인시 수지구 문정로 32,448170.0,16837.0,NaN,1,NaN,127.095522,37.323528

In [25]:
dfs = df[(df["상권업종소분류명"].str.contains("피부") | df["상권업종소분류명"].str.contains("성형"))]
dfs = dfs[dfs["시도명"] == "서울특별시"]
dfs

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
8,20808534,코원성형외과,NaN,S,의료,S01,병원,S01B08,정형/성형외과,Q86201,...,1168010700105920004010990,이가빌딩,서울특별시 강남구 논현로 826,135893.0,6025.0,NaN,4,NaN,127.028531,37.522223
31,20872995,고운나라성형외과,NaN,S,의료,S01,병원,S01B08,정형/성형외과,Q86201,...,1174010800100090005004868,NaN,서울특별시 강동구 천호대로 1032,134030.0,5379.0,NaN,3,NaN,127.126507,37.537333
44,20912401,아미가성형외과,NaN,S,의료,S01,병원,S01B08,정형/성형외과,Q86201,...,1165010100109020001015305,원등빌딩,서울특별시 서초구 방배로20길 4,137060.0,6664.0,NaN,3,NaN,126.995334,37.485498
94,21859520,새롬성형외과,NaN,S,의료,S01,병원,S01B08,정형/성형외과,Q86201,...,1156010500104250037035858,NaN,서울특별시 영등포구 경인로 835,150034.0,7305.0,NaN,NaN,NaN,126.905647,37.516310
164,22838864,김종서성형,NaN,S,의료,S01,병원,S01B08,정형/성형외과,Q86201,...,1168010700105990004010396,압구정빌딩,서울특별시 강남구 논현로 842,135893.0,6025.0,NaN,2,NaN,127.028712,37.524027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91183,16311408,더새로이보셀르성형외과의원,NaN,S,의료,S01,병원,S01B08,정형/성형외과,Q86201,...,1165010800113080026000001,강남역리가스퀘어,서울특별시 서초구 서초대로73길 42,137856.0,6612.0,307,3,311,127.024427,37.501222
91241,16109061,인터내셔널이미지업성형외과,NaN,S,의료,S01,병원,S01B08,정형/성형외과,Q86201,...,1165010600100190007019199,이미지업빌딩,서울특별시 서초구 나루터로 76,137903.0,6526.0,NaN,3,2,127.018077,37.515451
91243,16131207,UBA성형외과,NaN,S,의료,S01,병원,S01B08,정형/성형외과,Q86201,...,1168010700105010000000001,신사미타워,서울특별시 강남구 강남대로 616,135887.0,6035.0,NaN,5,502,127.019778,37.516843
91285,16131940,대한피부과학연구소,NaN,S,의료,S01,병원,S01B16,피부과,Q86201,...,1168010100108320007025977,황화빌딩,서울특별시 강남구 강남대로 320,135936.0,6252.0,NaN,NaN,1108,127.031028,37.491842
91287,16133165,가톨릭정형외과,NaN,S,의료,S01,병원,S01B08,정형/성형외과,Q86201,...,1168010800102370011008621,파크랜드빌딩,서울특별시 강남구 언주로 601,135546.0,6109.0,NaN,NaN,NaN,127.037765,37.508855

In [26]:
dfs["시군구명"].value_counts(normalize=True)

강남구     0.439184
서초구     0.145666
송파구     0.034960
마포구     0.029133
영등포구    0.028405
강서구     0.027677
광진구     0.026948
강동구     0.026948
중구      0.022578
은평구     0.022578
서대문구    0.021122
성북구     0.020393
동대문구    0.019665
양천구     0.018937
노원구     0.018937
중랑구     0.015295
성동구     0.012382
구로구     0.012382
관악구     0.012382
동작구     0.010197
강북구     0.008740
종로구     0.008012
용산구     0.007283
금천구     0.006555
도봉구     0.003642
Name: 시군구명, dtype: float64